---
args:
  polygraphy:
    - '--extra-index-url https://pypi.ngc.nvidia.com'
  torch: []
conditions:
  cuda-python:
   - cuda-python
  onnx-graphsurgeon:
   - onnx-graphsurgeon
  triton:
   - triton; platform_system != "Windows"
  numpy:
   - numpy==1.23.5; platform_system != "Windows"
  torch:
   - torch
packages:
 - cuda-python
 - cupy-cuda12x
 - numba
 - triton
 - torch
 - polygraphy
 - colored
 - numpy
 - onnx-graphsurgeon
 - pywin32
...
