[tool.poetry]
name = "trt-engine-explorer"
version = "0.1.5"
description = "NVIDIA's experimental tool to explore TRT engines"
authors = ["Silky Arora <silky.arora@flyzipline.com>"]
license = "Apache-2.0"
readme = "src/README.md"
homepage = "https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/experimental/trt-engine-explorer"
repository = "https://github.com/NVIDIA/TensorRT"
packages = [{include = "trex", from = "src"}]


[tool.poetry.dependencies]
python = "^3.8"
setuptools = "^68.2.2"
wheel = "^0.41.3"
protobuf = "^3.20.0"
onnx = "^1.12.0"
numpy = "^1.24.3"
pandas = "^1.5.3"
plotly = "^5.18.0"
graphviz = "^0.20.1"
netron = "^7.2.8"
ipywidgets = "8.0.2"
ipyfilechooser = "^0.6.0"
jupyterlab = "^3.4.3"
jupyter-dash = "^0.4.2"
pytest = "^6.2.5"
xlsxwriter = "^3.1.9"
flask = "2.1.2"
jupyter = "^1.0.0"
openpyxl = "^3.1.2"
kaleido = "0.2.1"
dtale = "^2.2.0"
traitlets = "5.9.0"
werkzeug = "2.0.1"
qgrid = "^1.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
