[GPT2.all.gpt2-large.generate_a]

label = '''
TensorRT is a Deep Learning compiler used for deep learning.\n\nTensorRT is a Deep Learning compiler used for deep learning. TensorFlow is a high-performance, open-source, cross-platform, high-performance, machine learning framework.\n\nTensorFlow is a high-performance,
'''

[GPT2.all.default.generate_a]

input = '''
TensorRT is a Deep Learning compiler used for deep learning.
'''

label = '''
TensorRT is a Deep Learning compiler used for deep learning.\n\nThe main goal of the project is to create a tool that can be used to train neural networks.\n\nThe main goal of the project is to create a tool that can be used to train neural networks. The main goal of the project is
'''

[GPT2.all.gpt2-large.generate_b]

label = '''
GPT-2 is a transformer based model pretrained on a large corpus.\n\nThe model is trained on the following data:\n\nThe corpus consists of the following text files:\n\nThe corpus is split into two parts:\n\nThe first part contains the text files from the first part of the corpus
'''

[GPT2.all.default.generate_b]

input = '''
GPT-2 is a transformer based model pretrained on a large corpus.
'''

label = '''
GPT-2 is a transformer based model pretrained on a large corpus.\n\nThe model is based on the following assumptions:\n\nThe model is based on the following assumptions:\n\nThe model is based on the following assumptions:\n\nThe model is based on the following assumptions:\n\nThe model
'''

[GPT2.all.gpt2-large.generate_c]

label = '''
If I fall asleep then I am going to wake up in 8 hours.\n\nI am going to wake up in 8 hours.\n\nI am going to wake up in 8 hours.\n\nI am going to wake up in 8 hours.\n\nI am going to wake up in 8 hours.\n
'''

[GPT2.all.default.generate_c]

input = '''
If I fall asleep then I am going to wake up in 8 hours.
'''

label = '''
If I fall asleep then I am going to wake up in 8 hours.\n\nI am not going to sleep for 8 hours.\n\nI am going to wake up in 8 hours.\n\nI am going to wake up in 8 hours.\n\nI am going to wake up in 8 hours.\n
'''
