# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

---
args:
  polygraphy:
    - '--extra-index-url https://pypi.ngc.nvidia.com'
conditions:
  onnx-graphsurgeon:
   - onnx-graphsurgeon
  onnx:
   - onnx==1.16.0; platform_system == "Windows"
  triton:
   - 'triton==3.1.0; (platform_system != "Windows" and python_version <= "3.8")'
   - 'triton==3.2.0; (platform_system != "Windows" and python_version >= "3.9")'
  numpy:
   - 'numpy==1.23.5; (platform_system != "Windows" and python_version <= "3.10")'
   - 'numpy==1.26.4; (platform_system != "Windows" and python_version >= "3.11")'
packages:
 - triton
 - torch
 - polygraphy
 - colored
 - numpy
 - onnx
 - onnx-graphsurgeon
...
